version: 2
jobs:
   build:
     working_directory: ~/gradle-pitest-plugin
     docker:
       - image: circleci/openjdk:8-jdk
     steps:
       - checkout
       - run: ./gradlew check
   funcTest:
     steps:
       - run: export TERM=dumb
       - run: ./gradew funcTest
