version: 2
jobs:
   build:
     working_directory: ~/gradle-pitest-plugin
     docker:
       - image: circleci/openjdk:8-jdk
         environment:
           TERM: dumb
     steps:
       - run:
           name: build-and-test
           command: |
             ./gradlew check
             ./gradlew funcTest

