version: 2
jobs:
   build:
     working_directory: ~/gradle-pitest-plugin
     docker:
       - image: circleci/openjdk:8-jdk
     steps:
       - checkout
       # How to set environment variable in yml file?
       - run: TERM=dumb ./gradlew check

